POST http://localhost:8000/auth/sign-up HTTP/1.1
Content-Type: application/json

{
    "name" : "Vasya",
    "username" : "vasyatko",
    "password": "qwerty"
}

###
POST http://localhost:8000/auth/sign-in HTTP/1.1
Content-Type: application/json

{
    "username" : "vasyatko",
    "password": "qwerty"
}

###

POST http://localhost:8000/api/lists HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NTE4OTcyNTYsImlhdCI6MTY1MTg1NDA1NiwidXNlcl9pZCI6Mn0.nq1YcwmYTA_wUokHKKT3Lax4FIGbiCMH6kME8Fngc7w

{
    "title" : "Список Важных дел",
    "description" : "Срочно нужно сделать"
}

###

GET http://localhost:8000/api/lists HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NTE4OTcyNTYsImlhdCI6MTY1MTg1NDA1NiwidXNlcl9pZCI6Mn0.nq1YcwmYTA_wUokHKKT3Lax4FIGbiCMH6kME8Fngc7w

###

GET http://localhost:8000/api/lists/4 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NTE4OTcyNTYsImlhdCI6MTY1MTg1NDA1NiwidXNlcl9pZCI6Mn0.nq1YcwmYTA_wUokHKKT3Lax4FIGbiCMH6kME8Fngc7w

###

DELETE http://localhost:8000/api/lists/3 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NTE5NjIzMzgsImlhdCI6MTY1MTkxOTEzOCwidXNlcl9pZCI6Mn0.EojOT9wvAngB01qedHY0V3etAk5IwyuARzawKgcfNXk

###

PUT http://localhost:8000/api/lists/4 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NTIwNjc1NjAsImlhdCI6MTY1MjAyNDM2MCwidXNlcl9pZCI6Mn0.ojLUqdpdDa1Ty5DR2bXAueoC6kWZ6X9i5I9MMLGrMyw

{
    "title" : "John Lennon"
}